### ISSUE TITLE
this project is dead?

### ISSUE THREAD

**Issue by CARocha** [istrategylabs/django-wordpress#21]
Hi, this projects is dead? or any people continue develop for compatibility with django1.10??

**Comment by jcarbaugh** [comment]
@CARocha the previous maintainer just transferred the project to me and ISL, my current employer, today. We'll be updating the app over the next couple weeks to get it working with Django 1.10 and incorporate some of the open PRs. Thanks!

**Comment by collinanderson** [comment]
I'm currently using code similar to this project in production if you guys need help. I'm pretty sure my code is compatible with 1.10 if you guys are having issues getting compatible.
